dist: trusty
sudo: required
services:
  - docker
script:
- sudo bash ./build-docker.sh
- ls -lahR deploy
deploy:
  provider: releases
  api_key:
    secure: uA6++jf4shmjbySEPMi6vaAoWKEByg9INfc+q7y1PucwWJw1u3W9nWYjbLE+ycurvjfICOp2tK3khSPqs9PciPc6yjCdAkFWg+07lgudmjQHocS7mVQO9asEFgMBXPs38lsccDo6owZ+Y6kd1ip1956vgg8dd0llGFlZZh1pZnwIhgrKVMSDuPzSluPMPpXiT+7qh/Gze9ohbMrIMlSsF8j3qLn1KZuT/9hEFGOJMMFr8nHvHK5tvVQubBLZQJWDcHPa1LzN3wmFWxd0LWn15aus2TvfZlDP9JTDpgq2ljuz5JtvBx/Ou0Cd8o14c0S28PEmdtF26umZ+WRJADpauSRo9XPpIOqsyrNrL1G59I4l4KnHilYetpfOv/994H4M4jcMAOa+Etx1W1X3gUfSmNvKi2vxlxQtDr3lyoKQdN6cV+5FE/Q3FZE0BqK+CWRSYgw/RFJWT9sn3D57e6SzEa8IY4gdkVHVPVfcXJoPCGnhOI00R+UAbDkpL4QA7mU5SuomzIYZ6ubpa1AgaA2PHhQoN+TkQk2VwHscGNzFFvaTZMAb3Cf38kdynlrMTR7BzqPmtB1krs0IkWX/LQwItCe/s/xiAc93WyJbF4z1wTvxSy58jdZAydDVhRlyYv9C5FQpU7nx6hmFZZP1MJ5CXCYptYPPMmfm+puBSMIhqhA=
  file: deploy/image-StreamingCamera-lite.zip
  on:
    repo: florian-asche/RaspberryPiStreamingCamera
    tags: true